version: '3.8'

volumes:
  redis-data:

services:
  redis:
    image: redis:latest
    ports:
         - 6379:6379
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes  

  ad-service:
    build:
      context: ./adservice
      dockerfile: Dockerfile

  cart-service:
    build:
      context: ./cartservice/src
      dockerfile: Dockerfile
    
  checkout-service:
    build:
      context: ./checkoutservice
      dockerfile: Dockerfile
   

  email-server:
    build:
      context: ./emailservice
      dockerfile: Dockerfile
   

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - PRODUCT_CATALOG_SERVICE_ADDR= product-catalog-service:3550
      - CURRENCY_SERVICE_ADDR = currency-service:7000
  
  currency-service:
    build:
      context: ./currencyservice
      dockerfile: Dockerfile
  

  recommendation-service:
    build:
      context: ./recommendationservice
      dockerfile: Dockerfile
   
  shipping-service:
    build:
      context: ./shippingservice
      dockerfile: Dockerfile
   

  product-catalog-service:
    build:
      context: ./productcatalogservice
      dockerfile: Dockerfile
    
  payment-service:
    build:
      context: ./paymentservice
      dockerfile: Dockerfile
  












    
