# Se definieron los servicios para el despliegue de la aplicación segun el contenido del 
# dockerfile de cada servicio.

version: '3.8'

volumes:
  redis-data:

services:
  redis:
    image: redis:latest
    ports:
         - 6379:6379
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes  

  ad-service:
    build:
      context: ./adservice
      dockerfile: Dockerfile

  cart-service:
    build:
      context: ./cartservice/src
      dockerfile: Dockerfile
    
  checkout-service:
    build:
      context: ./checkoutservice
      dockerfile: Dockerfile
   

  email-server:
    build:
      context: ./emailservice
      dockerfile: Dockerfile
  # El frontend no se pudo levantar. De acuerdo al error requeria las variables que estan definidas en 
  # el environment, las cuales se probaron con el nombre_contenedor:puerto, nombre_contenedor, se 
  # intentó con la IP, pero nada funcionó. Consecuentemente el frontend no levantó y el LB no llegó a 
  # las instancias.
  

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - PRODUCT_CATALOG_SERVICE_ADDR=docker-compose-product-catalog-service:3550
      - CURRENCY_SERVICE_ADDR=docker-compose-currency-service:7000
  
  currency-service:
    build:
      context: ./currencyservice
      dockerfile: Dockerfile
  

  recommendation-service:
    build:
      context: ./recommendationservice
      dockerfile: Dockerfile
   
  shipping-service:
    build:
      context: ./shippingservice
      dockerfile: Dockerfile
   

  product-catalog-service:
    build:
      context: ./productcatalogservice
      dockerfile: Dockerfile
    
  payment-service:
    build:
      context: ./paymentservice
      dockerfile: Dockerfile
# el servicio load_generator fue removido por sugerencia del profesor  












    
