version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./frontend/data:/app/data
    environment:
      - PRODUCT_CATALOG_SERVICE_ADDR=cartservice
#    depends_on:
#      - cartservice

#  cartservice:
#    build:
#      context: ./cartservice
#    ports:
 #     - 7070:7070
##      dockerfile: Dockerfile
    
   
    
  adservice:
    build:
      context: ./adservice
      dockerfile: Dockerfile
    ports:
      - 9555:9555
    depends_on:
      - frontend
    
